language: python
matrix:
  include:
  - env: DIST=py2_kern.docker
  - env: DIST=py2_manual.docker
  - env: DIST=py3_kern.docker
  - env: DIST=py3_manual.docker
services:
- docker
before_install:
- true
install:
- docker build . -t ${DIST} -f docker/${DIST}
before_script:
- true
script:
- pwd
- docker run -e TRAVIS_JOB_ID="$TRAVIS_JOB_ID" -e TRAVIS_BRANCH="$TRAVIS_BRANCH" -e DIST=${DIST} -it ${DIST}:latest "tests/run_tests.sh"
after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - export REPO=fx196/blimpy
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker tag ${DIST}:latest blimpy:${DIST}_$TAG
  - docker push $REPO
notifications:
  webhooks: https://coveralls.io/webhook
