language: python
python:
  - "2.7"
  - "3.5"
  
# command to install dependencies
install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libhdf5-serial-dev
  - pip install --upgrade pip setuptools wheel
  - pip install --only-binary=numpy,scipy numpy scipy
  - pip install matplotlib
  - CFLAGS=-I/usr/include/hdf5/serial pip install git+https://github.com/h5py/h5py
  - CFLAGS=-I/usr/include/hdf5/serial pip install git+https://github.com/kiyo-masui/bitshuffle
  - pip install .

# command to install dependencies
script: 
    - cd tests; coverage run --source=blimpy -m py.test

after_success: coveralls
    
branches:
  only:
    - master
