language: python
matrix:
  include:
  - env: DIST=py2_kern.docker
  - env: DIST=py2_manual.docker
  - env: DIST=py3_kern.docker
  - env: DIST=py3_manual.docker
services:
- docker
before_install:
- true
install:
- docker build . -t ${DIST} -f docker/${DIST}
- pip install coveralls pyyaml
before_script:
- true
script:
- pwd
- docker container ls -a
- docker image ls -a
- docker run -e TRAVIS_JOB_ID="$TRAVIS_JOB_ID" -e TRAVIS_BRANCH="$TRAVIS_BRANCH" -it ${DIST}:latest "tests/run_tests.sh"
after_success:
- coveralls
